### PR TITLE
gtk4 port

### LINKED ISSUE #333: It's time we switch to GTK 4
I think the steps will be:

- Comment out all clipboard/clipboards-manager/gdkatom stuff (yes, this will break the linkage).
- Make the rest build properly
- Uncomment gradually what has been commented, porting stuff along the way.

We should definitely do that before the v40 release

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #333 #344

### CODE REVIEW

**Comment by Keruspe** [comment]
This is not finished yet.

**Comment by Keruspe** [comment]
I think I'm mostly done locally. Latest blocker is https://gitlab.gnome.org/GNOME/gtk/-/issues/3818

**Comment by yochananmarqos** [comment]
It builds, but it says there's no no rule to make target 'install`. What am I missing?

**Comment by fareszr** [comment]
any eta ?

**Comment by Keruspe** [comment]
As you can see, I'm actively working on it.
I've fixed most issue now, a couple of things left still.

Also, third kid being due in the next days (+ me not being paid to do all that, since this is not part of my actual job) might add a bit of delay.

**Comment by Keruspe** [comment]
Main issues left :
- properly handle files
- hook "special atoms" back in g_paste_clipboard_update and g_paste_content_provider
- update my system to gnome 40 and test that everything works as expected

**Comment by fareszr** [comment]
> As you can see, I'm actively working on it.
> I've fixed most issue now, a couple of things left still.
> 
> Also, third kid being due in the next days (+ me not being paid to do all that, since this is not part of my actual job) might add a bit of delay.

no problem ! take your time

i would like to help with testing when its ready
just drop a zip file for the compiled extensions (couldn't figure out how to build it) and i will test it on gnome 40 fedora 34

**Comment by Keruspe** [comment]
> Main issues left :
> 
>     * properly handle files
> 
>     * hook "special atoms" back in g_paste_clipboard_update and g_paste_content_provider
> 
>     * update my system to gnome 40 and test that everything works as expected

1 is done
2 is half done

**Pull request closed without merging**
